<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32" started-at="2014-12-19T14:14:40Z" finished-at="2014-12-19T14:14:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32" started-at="2014-12-19T14:14:40Z" finished-at="2014-12-19T14:14:40Z">
      <class name="business.scenarios.KFPICTScenario">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:business.scenarios.KFPICTScenario@1d2068d]" name="beforeSuite" is-config="true" duration-ms="15" started-at="2014-12-19T19:44:40Z" finished-at="2014-12-19T19:44:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="FAIL" signature="beforeTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:business.scenarios.KFPICTScenario@1d2068d]" name="beforeTest" is-config="true" duration-ms="0" started-at="2014-12-19T19:44:40Z" finished-at="2014-12-19T19:44:40Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'ScenarioName' is required by @Configuration on method beforeTest but has not been marked @Optional or defined
in C:\Documents and Settings\prasannak\Local Settings\Temp\testng-eclipse--817619291\testng-customsuite.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'ScenarioName' is required by @Configuration on method beforeTest but has not been marked @Optional or defined
in C:\Documents and Settings\prasannak\Local Settings\Temp\testng-eclipse--817619291\testng-customsuite.xml
	at org.testng.internal.Parameters.createParameters(Parameters.java:155)
	at org.testng.internal.Parameters.createParameters(Parameters.java:358)
	at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:86)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:199)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="KFPICTScenarioMain(java.lang.String, java.lang.String, java.lang.String, java.util.HashMap)[pri:0, instance:business.scenarios.KFPICTScenario@1d2068d]" name="KFPICTScenarioMain" duration-ms="0" started-at="2014-12-19T19:44:40Z" finished-at="2014-12-19T19:44:40Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method KFPICTScenarioMain requires 4 parameters but 3 were supplied in the @Test annotation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method KFPICTScenarioMain requires 4 parameters but 3 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:198)
	at org.testng.internal.Parameters.createParameters(Parameters.java:134)
	at org.testng.internal.Parameters.createParameters(Parameters.java:358)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:450)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- KFPICTScenarioMain -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:business.scenarios.KFPICTScenario@1d2068d]" name="afterSuite" is-config="true" duration-ms="3389" started-at="2014-12-19T19:44:40Z" finished-at="2014-12-19T19:44:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- business.scenarios.KFPICTScenario -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
